### ISSUE TITLE
File format documentation?

### ISSUE THREAD

**Issue by hanetzer** [neivv/animosity#1]
In your [post](http://www.staredit.net/topic/17590/) you mention `Thanks to Farty for documenting the file formats.`,
I know its been a while but do you happen to have a link/reference to this documentation? I would just read the
source code, but I don't grok rust at all.

**Comment by neivv** [comment]
.dds.grp http://www.staredit.net/364375/
.anim http://www.staredit.net/364458/

And two things I have found out later that weren't documented there:
1) Dds.vr4 files for SD tilesets are a different variation that contains a 256-color palette and 8bpp frames
2) Foliage.anim files have some additional data that regular sprite.anim files don't

**Comment by hanetzer** [comment]
Many thanks. I managed to run into farty on discord and have gotten some good information.
For the record, this info request is for the sake of using stratagus/stargus with the new release.
